In [4]:
from patsy import demo_data
import pandas as pd
# 임의의 실수형 데이터
df = pd.DataFrame(demo_data("x1", "x2", "x3", "x4", "x5"))
df
df.boxplot()

<AxesSubplot:>

In [5]:
from sklearn.preprocessing import StandardScaler
# 평균 0, 표준편차 1이 되도록 스케일링
scaler = StandardScaler()
df2=scaler.fit_transform(df)
df3=pd.DataFrame(df2, columns=df.columns)
df3
df3.boxplot()

<AxesSubplot:>

In [6]:
import numpy as np
X = np.arange(7).reshape(7,1) # 7행 1열로 변환
X

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X2=scaler.fit_transform(X)
X2

array([[-1.5],
       [-1. ],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 1. ],
       [ 1.5]])

In [8]:
# 이상치(outlier)가 존재할 경우
# 1000 이라는 이상치를 추가
X2 = np.vstack([X, [[1000]]]) # 배열을 세로로 쌓는 함수
X2

array([[   0],
       [   1],
       [   2],
       [   3],
       [   4],
       [   5],
       [   6],
       [1000]])

In [9]:
# 이상치가 존재할 경우 스케일링을 했을 때 0에 수렴하지 않고 멀어지는 현상이 발생할 수 있다.
# 이것은 기계학습 모형의 예측력을 떨어뜨릴 수 있는 요인이 될 수 있다.
scaler.fit_transform(X2)

array([[-0.38705669],
       [-0.38402392],
       [-0.38099115],
       [-0.37795839],
       [-0.37492562],
       [-0.37189286],
       [-0.36886009],
       [ 2.64570872]])

In [10]:
# 이상치가 많은 데이터의 경우 RobustScaler를 사용한다.
# 중앙값 0, IQR(InterQuartile Range)이 1이 되도록 변환하므로 이상치가 있어도 대부분의 데이터가 0 주위로 모이게 된다.
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
scaler.fit_transform(X2)

array([[-1.00000000e+00],
       [-7.14285714e-01],
       [-4.28571429e-01],
       [-1.42857143e-01],
       [ 1.42857143e-01],
       [ 4.28571429e-01],
       [ 7.14285714e-01],
       [ 2.84714286e+02]])